name: aastk
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.13
  - pip
  - contourpy>=1.3.2
  - matplotlib>=3.10.1
  - numpy>=2.2.5
  - opentsne>=1.0.2
  - pandas>=2.2.3
  - pyyaml>=6.0.2
  - scikit-learn>=1.6.1
  - scipy>=1.15.3
  - diamond>=2.1.8
  - seqkit>=2.5.1
  - tqdm>=4.67.1
